import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bankGothic = localFont({
  src: "../public/bankgothic-md-bt/BankGothic Md BT.ttf",
  variable: "--font-bankgothic",
});

const neoform = localFont({
  src: "../public/neoform-font-1766056187-0/NeoformDemo-2v5zX.otf",
  variable: "--font-neoform",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bankGothic.variable} ${neoform.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
